### ISSUE TITLE
When the command `service:dev` throws an error, the engine is not stopped and the next use of `service:dev` doesn't stop the engine and the running service:

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#18]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/201
Originally created by @antho1404 on *Tue, 24 Mar 2020 08:58:05 GMT*

---
When the command `service:dev` throws an error, the engine is not stopped and the next use of `service:dev` doesn't stop the engine and the running service:
```
➜  js-sdk git:(bug/config-path) ./packages/cli/bin/run service:dev ../services/service-ethereum
  ✔ Start environment
  ✔ Compiling service
  ✖ Creating service
    → out of gas: out of gas in location: WritePerByte; gasWanted: 300000, gasUsed: 347768
    Starting service
    Fetching service's logs
Error: out of gas: out of gas in location: WritePerByte; gasWanted: 300000, gasUsed: 347768
    at API.<anonymous> (~/Development/MESG/js-sdk/packages/api/lib/lcd.js:58:23)
    at Generator.next (<anonymous>)
    at fulfilled (~/Development/MESG/js-sdk/packages/api/lib/lcd.js:5:58)



➜  js-sdk git:(bug/config-path) ./packages/cli/bin/run service:dev ../services/service-emit-event-interval
  ✔ Start environment
  ✔ Compiling service
  ✔ Creating service
  ✔ Starting service
  ✔ Fetching service's logs
(node:1) UnhandledPromiseRejectionWarning: Error: 2 UNKNOWN: create event: data invalid request: instance "En6ewB6q5Gh5s7V7E4ftTzkbFSV2ozeHgTB8QN7wMWAv" not found
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
EVENT[every_2_seconds]: {"timestamp":1584706450623}
EVENT[every_1_second]: {"timestamp":1584706450638}
EVENT[every_1_second]: {"timestamp":1584706451643}
EVENT[every_2_seconds]: {"timestamp":1584706452623}
EVENT[every_1_second]: {"timestamp":1584706452646}
EVENT[every_5_seconds]: {"timestamp":1584706453623}
EVENT[every_1_second]: {"timestamp":1584706453648}
EVENT[every_2_seconds]: {"timestamp":1584706454591}
EVENT[every_1_second]: {"timestamp":1584706454615}
^C  ✔ Stopping logs
  ✔ Stop environment
 ›   Warning: Event stream error: 1 CANCELLED: Cancelled
 ›   Warning: Result stream error: 1 CANCELLED: Cancelled


➜  js-sdk git:(bug/config-path) docker service list
]ID                  NAME                                                  MODE                REPLICAS            IMAGE                                                                     PORTS
fmp8nhmaj1co        engine                                                replicated          1/1                 mesg/engine                                                               *:1317->1317/tcp, *:26656->26656/tcp, *:50052->50052/tcp
iitonbjnjx28        engine-8nMhm14WhFSZr2dGAgrH1xe86mUZLrQUNY2jnbBzoQ3G   replicated          1/1                 sha256:d84c5f68c5994d42bdc2aab41a88e8a457f86380b26fd051f90adc321ad115b4
```

_Originally posted by @NicolasMahe in https://github.com/mesg-foundation/js-sdk/pull/197#issuecomment-601670084_

**Comment by antho1404** [comment]
fixed by https://github.com/liteflow-labs/liteflow-js/pull/35
