### ISSUE TITLE
Issue when installing on Linux (on DigitalOcean)

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#19]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/12
Originally created by @antho1404 on *Sun, 16 Jun 2019 13:33:44 GMT*

---
After a fresh install of node on DigitalOcean I can't install the `mesg-cli`

```bash
root@marketplace-service:~# npm i -g mesg-cli
/usr/bin/mesg-cli -> /usr/lib/node_modules/mesg-cli/bin/run

> secp256k1@3.7.1 install /usr/lib/node_modules/mesg-cli/node_modules/secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

npm ERR! path /root/.npm/_logs
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall scandir
npm ERR! Error: EACCES: permission denied, scandir '/root/.npm/_logs'
npm ERR!  { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'scandir',
npm ERR!   path: '/root/.npm/_logs' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).
glob error { [Error: EACCES: permission denied, scandir '/root/.npm/_logs']
  stack:
   'Error: EACCES: permission denied, scandir \'/root/.npm/_logs\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/root/.npm/_logs' }

> secp256k1@3.7.1 rebuild /usr/lib/node_modules/mesg-cli/node_modules/secp256k1
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.16.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/mesg-cli/node_modules/secp256k1/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/mesg-cli/node_modules/secp256k1/.node-gyp'
gyp ERR! System Linux 4.15.0-46-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/mesg-cli/node_modules/secp256k1
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.7.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@3.7.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Secp256k1 bindings compilation fail. Pure JS implementation will be used.

> ursa-optional@0.9.10 install /usr/lib/node_modules/mesg-cli/node_modules/ursa-optional
> node rebuild.js

ursaNative bindings compilation fail. This is not an issue. Modules that depend on it will use fallbacks.
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open './stdout.log'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at Object.<anonymous> (/usr/lib/node_modules/mesg-cli/node_modules/ursa-optional/rebuild.js:13:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ursa-optional@0.9.10 install: `node rebuild.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ursa-optional@0.9.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-16T13_32_15_041Z-debug.log
```

**Comment by antho1404** [comment]
fixed in version 2.4.0
