### ISSUE TITLE
Simulate transaction before broadcasting

### ISSUE THREAD

**Issue by antho1404** [liteflow-labs/liteflow-js#67]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/185
Originally created by @antho1404 on *Thu, 12 Mar 2020 07:15:24 GMT*

---
Right now the transaction is sent with no simulation. This means that there is no fee optimization and no checks before sending it. We should add this step of simulating the transaction and adjusting the fees based on the simulation.

**Comment by antho1404** [comment]
---

Migrated from https://github.com/mesg-foundation/js-sdk/issues/185#issuecomment-601656504
Originally created by @NicolasMahe on *Fri, 20 Mar 2020 11:38:13 GMT*

---
Could you quickly increase the hardcoded gas to much more?
Or put a flag / config to override it?
The service-ethereum cannot be deployed with the current gas limit:
```
➜  js-sdk git:(feature/task-refactoring) ✗ ./packages/cli/bin/run service:dev ../services/service-ethereum
  ✔ Starting environment
  ✔ Compiling service
  ✖ Creating service
    → out of gas: out of gas in location: WritePerByte; gasWanted: 300000, gasUsed: 349145
    Starting service
    Fetching service's logs
Error: out of gas: out of gas in location: WritePerByte; gasWanted: 300000, gasUsed: 349145
    at API.<anonymous> (~/Development/MESG/js-sdk/packages/api/lib/lcd.js:58:23)
    at Generator.next (<anonymous>)
    at fulfilled (~/Development/MESG/js-sdk/packages/api/lib/lcd.js:5:58)
```
