### ISSUE TITLE
flag --clean on command dev doesn't work if a service is still running

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/liteflow-js#96]
The flag `--clean` on command dev doesn't work if a service is still running:

```
liteflow dev ./ --clean
2020-05-07T12:41:28.968Z INFO › engine › cleaning environment
Error: (HTTP code 403) unexpected - error while removing network: network mesg_engine id aa9cef3cb4e856d6dba2d621c7cbcb3a8f8ca9f21c309f84bba7ee5d9e89e1e0 has active endpoints
    at ~/Development/liteflow-labs/liteflow-js/packages/cli/node_modules/docker-modem/lib/modem.js:239:17
    at getCause (~/Development/liteflow-labs/liteflow-js/packages/cli/node_modules/docker-modem/lib/modem.js:269:7)
    at Modem.buildPayload (~/Development/liteflow-labs/liteflow-js/packages/cli/node_modules/docker-modem/lib/modem.js:238:5)
    at IncomingMessage.<anonymous> (~/Development/liteflow-labs/liteflow-js/packages/cli/node_modules/docker-modem/lib/modem.js:214:14)
```
```
docker ps -a
CONTAINER ID        IMAGE                                                   COMMAND             CREATED             STATUS              PORTS                                            NAMES
8d8f6c8c1cf1        liteflow:FDvQhZTwYPay1CnurZ1GQowSVEhKQr6Q1p89p87T2PHS   "node index.js"     3 minutes ago       Up 3 minutes        0.0.0.0:3005->3005/tcp                           liteflow_srv_9XVDgSTnvZ9W4khoebKVZU9bLJmz1AR8ukKMaL549a2T
```

It could force delete all container using the prefix `liteflow_srv_`

**Comment by NicolasMahe** [comment]
outdated issue, command dev has been deleted in https://github.com/liteflow-labs/liteflow-js/pull/260
